services:
  db:
    container_name: zoomcamp-postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'ny_taxi'
    ports:
      - '5433:5432'
    volumes:
      - ./vol-pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: zoomcamp-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "8081:80"
    volumes:
      - ./vol-pgadmin_data:/var/lib/pgadmin
